# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/CHESHIRE/AURAVIRTUAL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/CHESHIRE/AURAVIRTUAL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/CHESHIRE/AURAVIRTUAL/CMakeFiles /Volumes/CHESHIRE/AURAVIRTUAL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/CHESHIRE/AURAVIRTUAL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Volumes/CHESHIRE/AURAVIRTUAL/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AURAVIRTUAL

# Build rule for target.
AURAVIRTUAL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AURAVIRTUAL
.PHONY : AURAVIRTUAL

# fast build rule for target.
AURAVIRTUAL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/build
.PHONY : AURAVIRTUAL/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/GLFW/src/CMakeFiles/glfw.dir/build.make lib/GLFW/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/GLFW/src/CMakeFiles/update_mappings.dir/build.make lib/GLFW/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/core/Application.o: src/core/Application.cpp.o
.PHONY : src/core/Application.o

# target to build an object file
src/core/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/Application.cpp.o
.PHONY : src/core/Application.cpp.o

src/core/Application.i: src/core/Application.cpp.i
.PHONY : src/core/Application.i

# target to preprocess a source file
src/core/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/Application.cpp.i
.PHONY : src/core/Application.cpp.i

src/core/Application.s: src/core/Application.cpp.s
.PHONY : src/core/Application.s

# target to generate assembly for a file
src/core/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/Application.cpp.s
.PHONY : src/core/Application.cpp.s

src/core/main.o: src/core/main.cpp.o
.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i
.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s
.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

src/math/Vector2D.o: src/math/Vector2D.cpp.o
.PHONY : src/math/Vector2D.o

# target to build an object file
src/math/Vector2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/math/Vector2D.cpp.o
.PHONY : src/math/Vector2D.cpp.o

src/math/Vector2D.i: src/math/Vector2D.cpp.i
.PHONY : src/math/Vector2D.i

# target to preprocess a source file
src/math/Vector2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/math/Vector2D.cpp.i
.PHONY : src/math/Vector2D.cpp.i

src/math/Vector2D.s: src/math/Vector2D.cpp.s
.PHONY : src/math/Vector2D.s

# target to generate assembly for a file
src/math/Vector2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/math/Vector2D.cpp.s
.PHONY : src/math/Vector2D.cpp.s

src/renderer/QueueFamily.o: src/renderer/QueueFamily.cpp.o
.PHONY : src/renderer/QueueFamily.o

# target to build an object file
src/renderer/QueueFamily.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/QueueFamily.cpp.o
.PHONY : src/renderer/QueueFamily.cpp.o

src/renderer/QueueFamily.i: src/renderer/QueueFamily.cpp.i
.PHONY : src/renderer/QueueFamily.i

# target to preprocess a source file
src/renderer/QueueFamily.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/QueueFamily.cpp.i
.PHONY : src/renderer/QueueFamily.cpp.i

src/renderer/QueueFamily.s: src/renderer/QueueFamily.cpp.s
.PHONY : src/renderer/QueueFamily.s

# target to generate assembly for a file
src/renderer/QueueFamily.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/QueueFamily.cpp.s
.PHONY : src/renderer/QueueFamily.cpp.s

src/renderer/Renderer.o: src/renderer/Renderer.cpp.o
.PHONY : src/renderer/Renderer.o

# target to build an object file
src/renderer/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/Renderer.cpp.o
.PHONY : src/renderer/Renderer.cpp.o

src/renderer/Renderer.i: src/renderer/Renderer.cpp.i
.PHONY : src/renderer/Renderer.i

# target to preprocess a source file
src/renderer/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/Renderer.cpp.i
.PHONY : src/renderer/Renderer.cpp.i

src/renderer/Renderer.s: src/renderer/Renderer.cpp.s
.PHONY : src/renderer/Renderer.s

# target to generate assembly for a file
src/renderer/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/Renderer.cpp.s
.PHONY : src/renderer/Renderer.cpp.s

src/renderer/triangle-vulkan.o: src/renderer/triangle-vulkan.c.o
.PHONY : src/renderer/triangle-vulkan.o

# target to build an object file
src/renderer/triangle-vulkan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/triangle-vulkan.c.o
.PHONY : src/renderer/triangle-vulkan.c.o

src/renderer/triangle-vulkan.i: src/renderer/triangle-vulkan.c.i
.PHONY : src/renderer/triangle-vulkan.i

# target to preprocess a source file
src/renderer/triangle-vulkan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/triangle-vulkan.c.i
.PHONY : src/renderer/triangle-vulkan.c.i

src/renderer/triangle-vulkan.s: src/renderer/triangle-vulkan.c.s
.PHONY : src/renderer/triangle-vulkan.s

# target to generate assembly for a file
src/renderer/triangle-vulkan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/renderer/triangle-vulkan.c.s
.PHONY : src/renderer/triangle-vulkan.c.s

src/scene/Object.o: src/scene/Object.cpp.o
.PHONY : src/scene/Object.o

# target to build an object file
src/scene/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/scene/Object.cpp.o
.PHONY : src/scene/Object.cpp.o

src/scene/Object.i: src/scene/Object.cpp.i
.PHONY : src/scene/Object.i

# target to preprocess a source file
src/scene/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/scene/Object.cpp.i
.PHONY : src/scene/Object.cpp.i

src/scene/Object.s: src/scene/Object.cpp.s
.PHONY : src/scene/Object.s

# target to generate assembly for a file
src/scene/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AURAVIRTUAL.dir/build.make CMakeFiles/AURAVIRTUAL.dir/src/scene/Object.cpp.s
.PHONY : src/scene/Object.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... AURAVIRTUAL"
	@echo "... glfw"
	@echo "... src/core/Application.o"
	@echo "... src/core/Application.i"
	@echo "... src/core/Application.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/math/Vector2D.o"
	@echo "... src/math/Vector2D.i"
	@echo "... src/math/Vector2D.s"
	@echo "... src/renderer/QueueFamily.o"
	@echo "... src/renderer/QueueFamily.i"
	@echo "... src/renderer/QueueFamily.s"
	@echo "... src/renderer/Renderer.o"
	@echo "... src/renderer/Renderer.i"
	@echo "... src/renderer/Renderer.s"
	@echo "... src/renderer/triangle-vulkan.o"
	@echo "... src/renderer/triangle-vulkan.i"
	@echo "... src/renderer/triangle-vulkan.s"
	@echo "... src/scene/Object.o"
	@echo "... src/scene/Object.i"
	@echo "... src/scene/Object.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Volumes/CHESHIRE/AURAVIRTUAL/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

